import logging
import random
from typing import List

from fastapi import APIRouter, Depends
from pydantic import BaseModel
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy import select
from datetime import datetime, timedelta, timezone

from database import get_db
from jwt_auth import AuthUser, require_service_auth
import models
import schemas

logger = logging.getLogger(__name__)

router = APIRouter(prefix="/voice-events", tags=["voice-events"])

# ── Chitchat stock (in-memory, pre-generated by Brain) ────────
_chitchat_stock: list[dict] = []
CHITCHAT_STOCK_MAX = 10


class ChitchatStockItem(BaseModel):
    message: str
    audio_url: str
    tone: str = "neutral"


@router.post("/", response_model=schemas.VoiceEvent)
async def create_voice_event(
    event: schemas.VoiceEventCreate,
    db: AsyncSession = Depends(get_db),
    _auth: AuthUser = Depends(require_service_auth),
):
    """Record a voice event from Brain speak tool."""
    db_event = models.VoiceEvent(
        message=event.message,
        audio_url=event.audio_url,
        zone=event.zone,
        tone=event.tone,
    )
    db.add(db_event)
    await db.commit()
    await db.refresh(db_event)
    return db_event


@router.get("/recent", response_model=List[schemas.VoiceEvent])
async def get_recent_voice_events(
    db: AsyncSession = Depends(get_db),
):
    """Return voice events from the last 60 seconds (for frontend polling)."""
    cutoff = datetime.now(timezone.utc) - timedelta(seconds=60)
    # Also ignore events older than 5 minutes (stale)
    max_age = datetime.now(timezone.utc) - timedelta(minutes=5)

    result = await db.execute(
        select(models.VoiceEvent)
        .where(models.VoiceEvent.created_at >= max_age)
        .where(models.VoiceEvent.created_at >= cutoff)
        .order_by(models.VoiceEvent.created_at.desc())
    )
    return result.scalars().all()


@router.post("/chitchat-stock")
async def push_chitchat_stock(
    item: ChitchatStockItem,
    _auth: AuthUser = Depends(require_service_auth),
):
    """Brain pushes a pre-generated chitchat item to stock."""
    if len(_chitchat_stock) >= CHITCHAT_STOCK_MAX:
        return {"ok": False, "reason": "stock full", "stock_size": len(_chitchat_stock)}
    _chitchat_stock.append(item.model_dump())
    return {"ok": True, "stock_size": len(_chitchat_stock)}


@router.get("/chitchat-stock/random")
async def pop_chitchat_stock():
    """Pop a random chitchat item from stock (for frontend audio-enable)."""
    if not _chitchat_stock:
        return {"ok": False, "reason": "empty"}
    item = random.choice(_chitchat_stock)
    _chitchat_stock.remove(item)
    return {"ok": True, **item}


@router.get("/chitchat-stock/status")
async def chitchat_stock_status():
    """Current stock level."""
    return {"stock_size": len(_chitchat_stock), "max": CHITCHAT_STOCK_MAX}
